export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_TOGGLE = 'REGISTER_TOGGLE'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const GET_USER = 'GET_USER'
export const EDIT_USER = 'EDIT_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const COUNTRY = 'COUNTRY'
export const STATE = 'STATE'
export const CITY = 'CITY'
export const CHECK_COOKIE = 'CHECK_COOKIE'

export const GET_UPLOAD_FILE ='GET_UPLOAD_FILE'
export const UPLOAD_FILE = 'UPLOAD_FILE'
export const LOADER = 'LOADER'
export const DELETEFILE = 'DELETEFILE'
export const DELETE_MULTIPLE_FILE = 'DELETE_MULTIPLE_FILE'